repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
- repo: https://codeberg.org/frnmst/md-toc
  rev: '8.2.2'
  hooks:
    - id: md-toc
      args: [-p, 'cmark', '-l6']
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17 
  hooks:
  - id: mdformat